version: '3.3'

services:

  api:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    container_name: blogs_api
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    env_file:
      - ".env"
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3
    container_name: blogs_pg
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ".env"
    ports:
      - "5432:5432"

